spring.application.name=notification-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/notifyhub
spring.datasource.username=postgres
spring.datasource.password=NotifyHub

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer   
app.kafka.notification-topic=notification-events