spring.application.name=notification-service
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/notifyhub
spring.datasource.username=postgres
spring.datasource.password=NotifyHub

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true